/* delete from Market; */

insert into Market (ID, AppNum, Name, Info) values (0, 0, 'Google Play', 'Google Play（前身为Android Market）是由Google为Android所开发的数位化应用发佈平台，包括数位媒体商店。它作为Android作业系统的官方应用商店，允许用户浏览和下载使用Android SDK开发并透过Google发布的应用程式。 Google Play也是数位媒体商店，提供音乐，杂志，书籍，电影和电视节目。它之前提供了Google硬件装置，直到2015年3月11日推出一个单独的线上硬件零售商Google Store。使用者可以透过Google Play免费或付费购买应用程式。透过Play商店行动应用直接下载到Android或Google TV装置，也可以透过Google Play网站直接部署应用安装在装置上。利用装置的硬件能力的应用可以透过必要的硬件属性（诸如运动传感器或前置相机）针对合适的用户。Android电子市场于2008年8月28日公开发表并于2008年10月22日正式上线; 2009年9月起陆续开始提供付费服务，Google Play于2012年3月6日推出，将Android Market，Google Music和Google电子书店整合在一个品牌下，标志著Google数位分销策略的转变。Google Play横幅下的服务包括：Google Play音乐，Google Play图书，Google Play书报摊，Google Play影视和Google Play游戏。Google Play商店已发布超过220万个应用程式，下载次数超过500亿次。');

insert into Market (ID, AppNum, Name, Info) values (1, 0, 'Google Play (English)', 'Google Play is a digital distribution service, including a digital media store, the Google Play Store (originally the Android Market), operated and developed by Google. It serves as the official app store for the Android operating system, allowing users to browse and download applications developed with the Android SDK and published through Google. Google Play also serves as a digital media store, offering music, magazines, books, movies, and television programs. It previously offered Google hardware devices for purchase until the introduction of a separate online hardware retailer, Google Store, on March 11, 2015. Applications are available through Google Play either free of charge or at a cost. They can be downloaded directly to an Android or Google TV device through the Play Store mobile app, or by deploying the application to a device from the Google Play website.Applications exploiting hardware capabilities of a device can be targeted to suitable users by requisite hardware attribute, such as a motion sensor or a front-facing camera. Google Play was launched on March 6, 2012, bringing together the Android Market, Google Music, and the Google eBookstore under one brand, marking a shift in Google\'s digital distribution strategy. The services operating under the Google Play banner are: Google Play Music, Google Play Books, Google Play Newsstand, Google Play Movies & TV, and Google Play Games. The Google Play store has reached over 2.2 million apps published and over 50 billion downloads.');

insert into Market (ID, AppNum, Name, Info) values (2, 0, '应用宝', '应用宝（原腾讯应用中心Android平台软件），是腾讯应用中心专为智能手机用户倾力打造的应用获取平台，应用宝致力于为客户提供丰富安全的手机应用资源和覆盖应用整个生命周期的一站式应用管理体验。目前此软件APP可以去网上下载，支持安卓、苹果、电脑版。应用宝为移动应用用户提供丰富海量的应用、游戏等产品的下载和服务，适配各类手机平台、移动终端。应用宝提供的移动应用软件和服务经过严格的软件测试、病毒扫描，运营人员为用户提供多种应用榜单和推荐，保证每位用户获得安全、优质的移动应用软件和服务。一切以用户价值为依归，提供真诚快捷有效的用户服务，努力为用户打造贴心、舒心、快乐、健康的移动应用服务平台。');

insert into Market (ID, AppNum, Name, Info) values (3, 0, '百度手机助手', '百度手机助手是Android手机的权威资源平台，拥有最全最好的应用、游戏、壁纸资源，帮助您在海量资源中精准搜索、高速下载、轻松管理，万千汇聚，一触即得。拥有海量免费优质安卓Android手机应用，提供极速下载，汇集最新最火热的安卓应用，好玩的安卓游戏、实用的安卓软件、每日劲爆推荐榜单，各种时下流行应用免费下载。海量资源：免费获取数十万款应用和游戏，同时凭借最强大的应用搜索功能以及认证系统，获得独一无二的好资源。省流量：更新国内领先技术，支持所有热门应用，大幅减少更新消耗的流量，最高节省90%流量。PC连接快速与电脑连接：手机、电脑不分家，管理手机更便捷。手机本地资源管理：直观高效的管理手机上的应用、图片、视频以及音乐文件，支持应用一键升级、文件一键删除。精准语音搜索：准确率高达96%，无需再手动输入。高速稳定下载：高速下载，服务稳定有保障；断点续传，应对一切网络状况。');

insert into Market (ID, AppNum, Name, Info) values (4, 0, '360手机助手', '360手机助手是一款智能手机的资源获取平台。可以为用户提供海量的游戏、软件、音乐、小说、视频、图片，通过这款软件可以轻松下载、安装、管理手机资源，拥有海量资源一键安装、绿色无毒安全无忧和应用程序方便管理等功能。所有提供信息资源，全部经过360安全检测中心的审核认证，绿色无毒，安全无忧。360手机助手帮助用户用最省流量、最快捷、最方便、最安全的方式获取网络资源通过数据线的方式将手机连接至PC，便可以通过360手机助手下载海量应用，电子书、视频、音乐、图片应有尽有，游戏、应用软件一应俱全。还可以通过它进行应用管理、任务管理、短信和联系人的备份和恢复、图片视频音乐等导入导出等等。360手机助手在Windows系统的电脑上使用， 360手机助手支持安装 了Android操作系统的智能手机（android 1.6及以上版本均可支持），Ophone2.0及以上版本亦可支持。');

insert into Market (ID, AppNum, Name, Info) values (5, 0, '华为应用市场', '华为应用市场是华为手机官方应用下载平台，也是华为用户首选应用市场，是基于Android系统的免费资源共享平台，依托华为全球化技术服务平台和实力雄厚的开发者群体，用户可以在应用市场上搜索、下载、管理、分享最贴心的移动应用，其中首创“开发者实名认证+3重系统检测+人工专员复检”安全保障机制，让用户下的放心，玩儿的畅快。应用审核团队每天严格监测高达上千款应用及游戏，内容运营团队在推荐每个应用之前都会输出专业的评测报告及游戏评分。保证每一款应用都经过系统+人工的双重检测，做业内最安全的应用市场。独家“一键下载安装”，让你的下载体验更方便更快捷！懒人更新（WLAN闲时下载更新包），智能启动更新（WIFI环境，电量高于30%，内存占用小于50%），不耗流量省量加速升级为你节省2/3的应用更新流量和下载时间。积分系统一站式服务，用户可以赚积分、兑奖，下载也可以变得更实惠更有趣。');

insert into Market (ID, AppNum, Name, Info) values (6, 0, '小米应用商店', '小米应用商店，是小米科技旗下米柚Android系统ROM中的一款安卓应用推荐软件。现已支持主流Android系统。小米应用商店的宗旨是：发现最好玩的安卓应用和游戏。每个应用都经过自动测试、安全扫描、人工审核三大检查，安全可靠！轻松发现热门的应用；每周编辑推荐精品应用，编辑独特的品位也能让你与众不同；支持增量升级，升级应用新版节省80%流量；支持忽略特定版本升级；支持省流量模式；国内独家支持Multiple-APK: 无论你的手机安卓系统版本是2.3还是4.0+，小米应用商店都可以智能过滤，提供适合你系统版本的最新应用。');

insert into Market (ID, AppNum, Name, Info) values (7, 0, '豌豆荚', '豌豆荚是一款在PC上使用的Android手机管理软件。豌豆荚是中国Android用户中人气、活跃度很高的“移动内容搜索”，也是中国移动互联网领域的创新企业。豌豆荚诞生于 2009 年12月，迄今安装量已超过4.2亿。豌豆荚专注于「移动内容搜索」领域的创新，并通过「应用内搜索」技术让用户搜索到千万量级的不重复应用、游戏、视频、电子书、主题、电影票、问答、旅游等内容，随时随地享受全面准确和直达行动的内容搜索消费体验。豌豆荚收录了超过45万款优质 Android 应用和游戏，以及 130 多家内容提供商提供的音乐、视频、电子书、壁纸和主题。让您的手机比您想象中更强大更好玩。豌豆荚提供的应用都清晰标示了安全、隐私、广告和官方验证信息。特色的“豌豆洗白白”功能，可将山寨应用、广告应用替换成官方版或无广告版，让您使用更放心。在手机上操作起来很繁琐的事情，在电脑上变得好高效。您可以使用豌豆荚收发短信，管理手机中的应用、联系人、图片和视频，备份手机数据到电脑和云端，管理手机就是这样得心应手。');

insert into Market (ID, AppNum, Name, Info) values (8, 0, '安卓市场', '安卓市场（HiMarket）是中国国内最早最大的安卓软件和游戏下载平台，为百度91无线旗下知名产品，为用户提供良好的手机软件服务。自2009年9月29日面世起，该产品致力于为广大安卓爱好者提供最全面、最快捷的软件、游戏下载服务。经过创新研发、精心耕耘，安卓市场上拥有最为丰富的应用种类，平均每日应用下载量高达几千万次，已发展为中国国内最大的拥有手机客户端、平板客户端、网页端和PC客户端（内置于91助手中）全方位下载渠道的应用市场。安卓市场由著名的安卓专业论坛安卓网开发，该市场是中国国内老牌的Android软件发布平台，原创中文软件涵盖量大，是一个全中文化的市场、本地化的程序应用，依托着安卓网开发者联盟的强大支持，每天不断有新鲜中文软件与大家见面。安卓市场提供“手机客户端”、“平板电脑客户端/PC端”和“网页端”等多种下载渠道，用户可以自由选择“手机直接下载”、“云推送”、“扫描二维码”和“电脑下载”等多种方式轻松获取安卓软件和游戏。安卓市场为您提供一站式的软件下载、管理和升级服务，用安卓手机，装安卓市场。');

insert into Market (ID, AppNum, Name, Info) values (9, 0, '安智市场', '安智成立于2010年2月，是中国移动互联网产品覆盖用户数量最多的平台之一，创始团队由国内最早从事Android Market项目的研发团队组成。目前，公司旗下拥有安智市场和安智论坛两大业务模块，公司致力于为全球华人Android系统手机用户提供便捷、愉悦的软件下载服务和体验，让Android手机变得更有用、更有趣。安智市场是目前中国最知名的Android系统手机应用软件免费下载平台。其人性化的设计，带来视觉和使用的双重享受，摒弃一切繁杂，拥有多种主题，适合不同的使用场景，让您随意享受下载的愉悦。安智市场具有急速、极全的特点，让你在找到你想要的任何应用与游戏的同时，体验非一般的下载速度。对待恶意软件，安智市场采用系统加人工的双重审核，让用户使用安全、放心。上安智，下软件——2亿用户的见证与选择。每天软件下载数量超过2000万次，覆盖手机、网页、平板三大渠道，想怎么下，就怎么下！');

insert into Market (ID, AppNum, Name, Info) values (10, 0, '91应用中心', '91助手是最受广大智能手机用户喜爱的中文应用市场，是国内最大、最具影响力的智能终端管理工具，也是全球唯一跨终端、跨平台的内容分发平台。智能贴心的操作体验，最多最安全可靠的资源让其成为亿万用户的共同选择。91助手移动端（手机版）覆盖安卓（Android）及苹果（iOS）两大主流智能平台。用户不仅可以省时省流量地下载各类应用，还能够一站式获得主题、壁纸、铃声等内容。91助手支持USB（数据线）连接、WiFi无线连接，及多设备同时接入。您可以使用该软件实现对手机上的基础资料(如：联系人、短信、通话记录、文件、程序、图片、音乐、视频、电子书、进程、壁纸、铃声等)的管理。同时，您还可以通过我们丰富的资源开放平台，下载最新最热门的游戏、应用、音乐.铃声、图片.壁纸、电影.视频、电子书、手机主题，个性化您的爱机。');

insert into Market (ID, AppNum, Name, Info) values (11, 0, 'OPPO软件商店', 'NearMe是专业为OPPO智能手机打造的移动互联网内容与服务品牌。NearMe在线服务涉及移动互联网中三个分类，共有六款产品。分别是，提供内容服务的产品：NearMe市场(软件商店)、NearMe音乐、NearMe阅读；提供社交服务的产品：NearMe游戏中心；提供云服务的产品：NearMe同步及找回手机。此外，还有贯穿各产品的服务体系——个人中心，它是提供NearMe注册用户进行“个人信息管理、支付管理、密码管理”的基础构架。NearMe市场给用户提供总数过万的游戏、软件、铃声、壁纸、主题等优质手机资源，市面上的热门、精品在这里都能找到。此外，NearMe官方会每日推荐精华专题给用户，方便用户获取最优资源。');

insert into Market (ID, AppNum, Name, Info) values (12, 0, 'PP助手', 'PP助手是一个支持iOS和Android两大系统智能设备的应用下载平台，满足用户需求，不断获取年轻用户的喜好。2015年，2015年是PP助手接入阿里系资源全面提升平台分发优势的一年，整合阿里系强大的数据资源、流量资源，在未来的移动应用分发市场，应该会成为一支不可忽视的重要力量。PP助手安卓版是一款支持所有安卓系统设备的管理工具，提供软件、游戏、壁纸、铃声资源的下载安装。与同类软件相比，它具有绿色官方资源、资源有效管理、界面交互独到、操作流畅、下载省流量有速度、资源海量等优势。PP助手安卓版成立至今1周年，依托阿里巴巴移动事业群，乃至整个阿里巴巴体系，其用户量及日分发量已经冲进市场第一序列，并成为安卓用户必装的应用之一，对用户来说，其海量资源，完全满足用户对游戏、应用安全下载的需要。为了整合资源，PP助手安卓版已经与淘宝打通，成为国内首个可以赚钱的手机助手。用户量及日分发量的强大基数，以及用户的喜爱，为PP助手安卓版独立发展单机手游分发，提供了实力支持。');
